# Generated by Django 5.0.6 on 2024-07-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0002_remove_user_id_user_user_id'),
    ]

    operations = [
    ]
