# Generated by Django 5.0.6 on 2024-07-08 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0003_auto_20240704_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('creator_id', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimonyapp.user')),
            ],
        ),
    ]
