# Generated by Django 5.0.6 on 2024-08-04 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0010_register_remove_login_user_id_delete_additionalinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimonyapp.register')),
            ],
        ),
    ]
