# Generated by Django 5.0.6 on 2024-08-04 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0011_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='reg',
            new_name='reg_id',
        ),
        migrations.AddField(
            model_name='login',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
