# Generated by Django 5.0.6 on 2024-08-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0012_rename_reg_login_reg_id_login_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.RemoveField(
            model_name='login',
            name='reg_id',
        ),
    ]
