# Generated by Django 5.0.6 on 2024-08-06 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0013_remove_login_last_login_remove_login_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='reg_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matrimonyapp.register'),
            preserve_default=False,
        ),
    ]
