# Generated by Django 5.0.6 on 2024-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0017_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='register',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
