# Generated by Django 5.0.6 on 2024-08-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0022_remove_education_college_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_blocked',
        ),
    ]
