# Generated by Django 5.0.6 on 2024-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0023_remove_register_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(choices=[('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Platinum Plus', 'Platinum Plus'), ('Gold Plus', 'Gold Plus'), ('Diamond Plus', 'Diamond Plus')], max_length=100, unique=True)),
                ('plan_details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField()),
            ],
        ),
    ]
