# Generated by Django 5.0.6 on 2024-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0029_register_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='education',
            name='reg_id',
        ),
        migrations.RemoveField(
            model_name='familydetails',
            name='reg_id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='reg_id',
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='reg_id',
        ),
        migrations.RemoveField(
            model_name='register',
            name='reset_password_token',
        ),
        migrations.RemoveField(
            model_name='register',
            name='token_expiry',
        ),
        migrations.AlterField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='FamilyDetails',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
