# Generated by Django 5.0.6 on 2024-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0031_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
