# Generated by Django 5.0.6 on 2024-08-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0035_personalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='country',
        ),
        migrations.RemoveField(
            model_name='register',
            name='location',
        ),
        migrations.RemoveField(
            model_name='register',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='register',
            name='religion',
        ),
        migrations.AddField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
