# Generated by Django 5.0.6 on 2024-08-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0036_remove_register_country_remove_register_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
