# Generated by Django 5.0.6 on 2024-08-12 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0037_personalinfo_location_personalinfo_mother_tongue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='reg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimonyapp.register'),
        ),
    ]
