# Generated by Django 5.0.6 on 2024-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0038_alter_login_reg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='register',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
