# Generated by Django 5.0.6 on 2024-08-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0039_remove_personalinfo_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='location',
            new_name='spoken_language',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='caste',
            field=models.CharField(blank=True, choices=[('catholic', 'Catholic'), ('orthodox', 'Orthodox'), ('general', 'General')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='physical_status',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('differently-abled', 'Differently-abled')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='height',
            field=models.CharField(blank=True, choices=[('150cm', '150 cm'), ('155cm', '155 cm'), ('160cm', '160 cm'), ('165cm', '165 cm'), ('170cm', '170 cm'), ('175cm', '175 cm'), ('180cm', '180 cm')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mother_tongue',
            field=models.CharField(blank=True, choices=[('malayalam', 'Malayalam'), ('tamil', 'Tamil'), ('hindi', 'Hindi'), ('english', 'English')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('christian', 'Christian'), ('hindu', 'Hindu'), ('muslim', 'Muslim'), ('sikh', 'Sikh'), ('buddhist', 'Buddhist')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='weight',
            field=models.CharField(blank=True, choices=[('50kg', '50 kg'), ('55kg', '55 kg'), ('60kg', '60 kg'), ('65kg', '65 kg'), ('70kg', '70 kg'), ('75kg', '75 kg'), ('80kg', '80 kg')], max_length=10, null=True),
        ),
    ]
