# Generated by Django 5.0.6 on 2024-08-22 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0040_rename_location_personalinfo_spoken_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='reg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimonyapp.register'),
        ),
    ]
