# Generated by Django 5.0.6 on 2024-08-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0041_alter_personalinfo_reg_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
