# Generated by Django 5.0.6 on 2024-08-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0042_delete_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('hobbies', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('annual_income', models.CharField(blank=True, max_length=50)),
                ('about_me', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('mother_tongue', models.CharField(blank=True, max_length=50)),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='matrimonyapp.register')),
            ],
        ),
    ]
