# Generated by Django 5.0.6 on 2024-08-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0044_remove_profile_about_me_remove_profile_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('school_passout_year', models.IntegerField()),
                ('school_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plus_two_name', models.CharField(max_length=255)),
                ('plus_two_passout_year', models.IntegerField()),
                ('plus_two_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('degree_institution_name', models.CharField(max_length=255)),
                ('degree_passout_year', models.IntegerField()),
                ('degree_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('degree_name', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimonyapp.register')),
            ],
        ),
    ]
