# Generated by Django 5.0.6 on 2024-08-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0046_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='reg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimonyapp.register'),
        ),
    ]
