# Generated by Django 5.0.6 on 2024-08-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0049_profile_age_profile_complexion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipplan',
            old_name='plan_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='plan_name',
        ),
    ]
