# Generated by Django 5.0.6 on 2024-09-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0050_rename_plan_id_membershipplan_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
