# Generated by Django 5.0.6 on 2024-09-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0052_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='compressed_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/compressed_images/'),
        ),
    ]
