# Generated by Django 5.0.6 on 2024-11-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0063_remove_profileview_viewed_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
