# Generated by Django 5.0.6 on 2024-11-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyapp', '0064_delete_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='MatchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('preferred_height', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_religion', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_caste', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_education', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_income', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_family_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_physical_status', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matrimonyapp.register')),
            ],
        ),
    ]
