from django.urls import path
from . import views

urlpatterns = [
    # Your existing URLs
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('profile/<str:connect_id>/', views.profile_view, name='profile'),
    path('education/<str:connect_id>/', views.education_view, name='education'),
    path('contact/<str:connect_id>/', views.contact_view, name='contact'),
    path('profilecreate/<str:connect_id>/', views.profilecreate_view, name='profilecreate'),
    path('mainpage/<str:connect_id>/', views.mainpage_view, name='mainpage'),
    path('myprofile/', views.myprofile_view, name='myprofile'),
    path('addyourstory/', views.addyourstory_view, name='addyourstory_view'),
    path('<str:connect_id>/upload-photo/', views.uploadphoto_view, name='uploadphoto'),
    path('profile-completion/<str:connect_id>/', views.profilecompletion_view, name='profilecompletion'),
    path('edit-primary-info/<str:connect_id>/', views.edit_primary_info, name='edit_primary_info'),
    path('profile/<str:connect_id>/edit/hobbies/', views.edit_hobbies_lifestyle, name='edit_hobbies_lifestyle'),
    path('family/<str:connect_id>/edit/', views.edit_family_info, name='edit_family_info'),
    path('contact/<str:connect_id>/edit/', views.edit_contact_info, name='edit_contact_info'),
    path('profile/<str:connect_id>/view_profile/', views.view_profile, name='view_profile'),
     path('<str:connect_id>/send-interest/', views.send_interest, name='send_interest'),
    path('admin-dashboard/', views.admin_page, name='admin_page'),
    path('logout/', views.logout_view, name='logout'),
    path('plans/', views.plans_list, name='plans_list'),
    path('plans/<int:plan_id>/', views.plan_detail, name='plan_detail'),
    path('plans/add/', views.add_plan, name='add_plan'),
    path('plans/<int:plan_id>/edit/', views.edit_plan, name='edit_plan'),
          path('plans/payment/<str:connect_id>/', views.payment_plans, name='payment_plans'),
    path('create-order/', views.create_order, name='create_order'),
    path('verify-payment/', views.verify_payment, name='verify_payment'),
    path('payment-success/<str:connect_id>/', views.payment_success, name='payment_success'),
path('matches/<str:connect_id>/', views.find_matches, name='find_matches'),
path('search/<str:connect_id>/', views.advanced_search, name='advanced_search'),
path('<str:connect_id>/block/<str:profile_id>/', views.block_profile, name='block_profile'),
    path('<str:connect_id>/unblock/<str:profile_id>/', views.unblock_profile, name='unblock_profile'),
    path('<str:connect_id>/blocked-profiles/', views.blocked_profiles, name='blocked_profiles'),
    path('toggle-shortlist/<str:connect_id>/', views.toggle_shortlist, name='toggle_shortlist'),
       path('sent-requests/<str:connect_id>/', views.view_sent_requests, name='view_sent_requests'),
       path('<str:connect_id>/withdraw-request/', views.withdraw_request, name='withdraw_request'),
 path('<str:connect_id>/interests/received/', views.received_interests, name='received_interests'),
    path('<str:connect_id>/interests/respond/', views.respond_to_interest, name='respond_to_interest'),
        path('success-stories/', views.success_stories_view, name='success_stories'),
        path('upload-photo/<str:connect_id>/', views.uploadphoto_view, name='uploadphoto'),
    path('approve-story/<int:story_id>/', views.approve_story, name='approve_story'),
    path('reject-story/<int:story_id>/', views.reject_story, name='reject_story'),
     path('blessed-couples/', views.blessed_couples, name='blessed_couples'),
         path('about-contact/', views.about_contact_view, name='about_contact'),
            path('analyze-image/', views.analyze_image, name='analyze_image'),
]